# Generated by Django 4.1.5 on 2023-01-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='')),
                ('complication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='complications.complication')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-title'],
            },
        ),
    ]
