# Generated by Django 4.1.5 on 2023-01-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complication',
            options={'ordering': ['-title'], 'verbose_name': 'Complication', 'verbose_name_plural': 'Complications'},
        ),
    ]
