# Generated by Django 4.1.5 on 2023-01-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['-title'], 'verbose_name': 'Profession', 'verbose_name_plural': 'Professions'},
        ),
        migrations.RemoveField(
            model_name='profession',
            name='direction',
        ),
        migrations.AddField(
            model_name='profession',
            name='direction',
            field=models.ManyToManyField(related_name='professions', to='directions.direction'),
        ),
    ]
