# Generated by Django 4.1.5 on 2023-01-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
        ('professions', '0002_alter_profession_options_remove_profession_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='direction',
        ),
        migrations.AddField(
            model_name='profession',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='directions.direction'),
        ),
    ]
